#@Value
encode:
  typeA: typeA
  typeB: typeB
#@ConfigurationPropertie
#@Profile config
spring:
  profiles:
    active:
    #    - mysql
    #    - postgre-sql
    #    - spring-data-query
    #    - spring-data-projection
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: tlcn092022@gmail.com
  #    password: TLcn.092022
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #      starttls:
  #        enable: true
